USE master
GO

DROP DATABASE IF EXISTS HazhozszallitoCegek 
GO

CREATE DATABASE HazhozszallitoCegek 
GO

USE HazhozszallitoCegek

CREATE TABLE HazhozszallitoCegek(
	HCID INT IDENTITY,
	Nev VARCHAR(50),
	Elerhetoseg VARCHAR(50)
	CONSTRAINT PK_HazhozszallitoCegek_HCID PRIMARY KEY (HCID)
);

CREATE TABLE Futarok(
	FID INT IDENTITY,
	Fizetes INT,
	Nev VARCHAR(50),
	Cim VARCHAR(100),
	HCID INT,
	CONSTRAINT PK_Futarok_FID PRIMARY KEY (FID),
	CONSTRAINT FK_Futarok_HCID FOREIGN KEY (HCID) REFERENCES HazhozszallitoCegek(HCID)
);

CREATE TABLE Vevok(
	VID INT IDENTITY,
	Nev VARCHAR(50),
	Lakcim VARCHAR(100),
	Telefonszam VARCHAR(15),
	CONSTRAINT PK_Vevok_VID PRIMARY KEY (VID)
);

CREATE TABLE Ettermek(
	EID INT IDENTITY,
	Nev VARCHAR(50),
	Cim VARCHAR(100),
	CONSTRAINT PK_Ettermek_EID PRIMARY KEY(EID)
);

CREATE TABLE Etelek(
	ETID INT IDENTITY,
	Nev VARCHAR(30),
	Leiras VARCHAR(200),
	Ar FLOAT,
	EID INT,
	CONSTRAINT PK_Etelek_ETID PRIMARY KEY (ETID),
	CONSTRAINT FK_Etelek_EID FOREIGN KEY (EID) REFERENCES Ettermek(EID)
);

CREATE TABLE Rendelesek(
	RID INT IDENTITY,
	Ar FLOAT,
	Datum DATETIME,
	HCID INT,
	VID INT,
	CONSTRAINT PK_Rendelesek_RID PRIMARY KEY (RID),
	CONSTRAINT FK_Rendelesek_HCID FOREIGN KEY (HCID) REFERENCES HazhozszallitoCegek(HCID),
	CONSTRAINT FK_Rendelesek_VID FOREIGN KEY (VID) REFERENCES Vevok(VID)
);

CREATE TABLE Tartalmaz(
	ETID INT,
	RID INT,
	CONSTRAINT PK_Tartalmaz_ETID_RID PRIMARY KEY (ETID, RID),
	CONSTRAINT FK_Tartalmaz_ETID FOREIGN KEY (ETID) REFERENCES Etelek(ETID),
	CONSTRAINT FK_Tartalmaz_RID FOREIGN KEY (RID) REFERENCES Rendelesek(RID),
);