USE DeliveryCompanies
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT * FROM Foods WHERE FoodPrice = 10.99
-- beszurunk egy sort 10.99 arral

SELECT * FROM Foods WHERE FoodPrice = 10.99
ROLLBACK